services:
  server:
    build:
      context: .
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - elasticsearch
      - kibana
  migration:
    build: .
    command: npx sequelize-cli db:migrate
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mypass
    volumes:
      - /var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
    restart: unless-stopped
  
  kibana:
   image: docker.elastic.co/kibana/kibana-oss:6.7.2
   container_name: kibana
   ports:
     - 5601:5601

volumes:
  elasticsearch-data: